name: Fetch Static Secrets example

'on': pull

jobs:
  fetch_secrets:
    runs-on: self-hosted
    # runs-on: 'ubuntu-latest'
    permissions:
      id-token: write
      contents: read
    env:
      ACTIONS_STEP_DEBUG: true
    steps:
    - name: Fetch static secrets from Akeyless
      uses: akeyless-community/akeyless-github-action@v1.0.1
      # uses: LanceMcCarthy/akeyless-action@v3
      id: fetch-secrets
      with:
        access-id: '${{ secrets.ACCESS_ID }}'
        access-type: jwt
        export-secrets-to-outputs: true
        export-secrets-to-environment: true
        static-secrets: |
          - name: "cicd/for-github-actions-dfc"
            output-name: "my_github_actions_secret"
        # static-secrets: '{"cicd/for-github-actions-dfc":"my_github_actions_secret"}'
        api-url: "https://cm-ninja.kiukairor.com/akeyless-api/v2/"
   
    - name: Use Akeyless secret (environment variable)
      env:
        SECRET: ${{ env.my_github_actions_secret }}
      run: |
        # # Use the secret securely within this step
        echo "Doing something with $SECRET"
        echo "ui ui uiiii"
     
    - name: Use Akeyless secret (step output)
      run: |
        # Use the secret securely within this step
        echo "Doing something with ${{ steps.fetch-secrets.outputs.my_github_actions_secret }}"
        echo "ui ui uiiii again"
